name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Webhook
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
